# Generated by Django 2.2 on 2019-04-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190429_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
